/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ExtensionsV1beta1IdRange : IDRange provides a min/max of an allowed range of IDs. Deprecated: use IDRange from policy API Group instead.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ExtensionsV1beta1IdRange {
  /// max is the end of the range, inclusive.
  #[serde(rename = "max")]
  max: i64,
  /// min is the start of the range, inclusive.
  #[serde(rename = "min")]
  min: i64
}

impl ExtensionsV1beta1IdRange {
  /// IDRange provides a min/max of an allowed range of IDs. Deprecated: use IDRange from policy API Group instead.
  pub fn new(max: i64, min: i64) -> ExtensionsV1beta1IdRange {
    ExtensionsV1beta1IdRange {
      max: max,
      min: min
    }
  }

  pub fn set_max(&mut self, max: i64) {
    self.max = max;
  }

  pub fn with_max(mut self, max: i64) -> ExtensionsV1beta1IdRange {
    self.max = max;
    self
  }

  pub fn max(&self) -> &i64 {
    &self.max
  }


  pub fn set_min(&mut self, min: i64) {
    self.min = min;
  }

  pub fn with_min(mut self, min: i64) -> ExtensionsV1beta1IdRange {
    self.min = min;
    self
  }

  pub fn min(&self) -> &i64 {
    &self.min
  }


}



