/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sKubernetesPkgApisBatchV1JobSpec : JobSpec describes how the job execution will look like.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApisBatchV1JobSpec {
  /// Optional duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
  #[serde(rename = "activeDeadlineSeconds")]
  active_deadline_seconds: Option<i64>,
  /// Specifies the desired number of successfully finished pods the job should be run with.  Setting to nil means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
  #[serde(rename = "completions")]
  completions: Option<i32>,
  /// manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://git.k8s.io/community/contributors/design-proposals/selector-generation.md
  #[serde(rename = "manualSelector")]
  manual_selector: Option<bool>,
  /// Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
  #[serde(rename = "parallelism")]
  parallelism: Option<i32>,
  #[serde(rename = "selector")]
  selector: Option<::models::IoK8sApimachineryPkgApisMetaV1LabelSelector>,
  #[serde(rename = "template")]
  template: ::models::IoK8sKubernetesPkgApiV1PodTemplateSpec
}

impl IoK8sKubernetesPkgApisBatchV1JobSpec {
  /// JobSpec describes how the job execution will look like.
  pub fn new(template: ::models::IoK8sKubernetesPkgApiV1PodTemplateSpec) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    IoK8sKubernetesPkgApisBatchV1JobSpec {
      active_deadline_seconds: None,
      completions: None,
      manual_selector: None,
      parallelism: None,
      selector: None,
      template: template
    }
  }

  pub fn set_active_deadline_seconds(&mut self, active_deadline_seconds: i64) {
    self.active_deadline_seconds = Some(active_deadline_seconds);
  }

  pub fn with_active_deadline_seconds(mut self, active_deadline_seconds: i64) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.active_deadline_seconds = Some(active_deadline_seconds);
    self
  }

  pub fn active_deadline_seconds(&self) -> Option<&i64> {
    self.active_deadline_seconds.as_ref()
  }

  pub fn reset_active_deadline_seconds(&mut self) {
    self.active_deadline_seconds = None;
  }

  pub fn set_completions(&mut self, completions: i32) {
    self.completions = Some(completions);
  }

  pub fn with_completions(mut self, completions: i32) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.completions = Some(completions);
    self
  }

  pub fn completions(&self) -> Option<&i32> {
    self.completions.as_ref()
  }

  pub fn reset_completions(&mut self) {
    self.completions = None;
  }

  pub fn set_manual_selector(&mut self, manual_selector: bool) {
    self.manual_selector = Some(manual_selector);
  }

  pub fn with_manual_selector(mut self, manual_selector: bool) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.manual_selector = Some(manual_selector);
    self
  }

  pub fn manual_selector(&self) -> Option<&bool> {
    self.manual_selector.as_ref()
  }

  pub fn reset_manual_selector(&mut self) {
    self.manual_selector = None;
  }

  pub fn set_parallelism(&mut self, parallelism: i32) {
    self.parallelism = Some(parallelism);
  }

  pub fn with_parallelism(mut self, parallelism: i32) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.parallelism = Some(parallelism);
    self
  }

  pub fn parallelism(&self) -> Option<&i32> {
    self.parallelism.as_ref()
  }

  pub fn reset_parallelism(&mut self) {
    self.parallelism = None;
  }

  pub fn set_selector(&mut self, selector: ::models::IoK8sApimachineryPkgApisMetaV1LabelSelector) {
    self.selector = Some(selector);
  }

  pub fn with_selector(mut self, selector: ::models::IoK8sApimachineryPkgApisMetaV1LabelSelector) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.selector = Some(selector);
    self
  }

  pub fn selector(&self) -> Option<&::models::IoK8sApimachineryPkgApisMetaV1LabelSelector> {
    self.selector.as_ref()
  }

  pub fn reset_selector(&mut self) {
    self.selector = None;
  }

  pub fn set_template(&mut self, template: ::models::IoK8sKubernetesPkgApiV1PodTemplateSpec) {
    self.template = template;
  }

  pub fn with_template(mut self, template: ::models::IoK8sKubernetesPkgApiV1PodTemplateSpec) -> IoK8sKubernetesPkgApisBatchV1JobSpec {
    self.template = template;
    self
  }

  pub fn template(&self) -> &::models::IoK8sKubernetesPkgApiV1PodTemplateSpec {
    &self.template
  }


}



