/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec : MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
  #[serde(rename = "object")]
  object: Option<::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ObjectMetricSource>,
  #[serde(rename = "pods")]
  pods: Option<::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1PodsMetricSource>,
  #[serde(rename = "resource")]
  resource: Option<::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ResourceMetricSource>,
  /// type is the type of metric source.  It should match one of the fields below.
  #[serde(rename = "type")]
  _type: String
}

impl IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
  /// MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
  pub fn new(_type: String) -> IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
    IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
      object: None,
      pods: None,
      resource: None,
      _type: _type
    }
  }

  pub fn set_object(&mut self, object: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ObjectMetricSource) {
    self.object = Some(object);
  }

  pub fn with_object(mut self, object: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ObjectMetricSource) -> IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
    self.object = Some(object);
    self
  }

  pub fn object(&self) -> Option<&::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ObjectMetricSource> {
    self.object.as_ref()
  }

  pub fn reset_object(&mut self) {
    self.object = None;
  }

  pub fn set_pods(&mut self, pods: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1PodsMetricSource) {
    self.pods = Some(pods);
  }

  pub fn with_pods(mut self, pods: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1PodsMetricSource) -> IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
    self.pods = Some(pods);
    self
  }

  pub fn pods(&self) -> Option<&::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1PodsMetricSource> {
    self.pods.as_ref()
  }

  pub fn reset_pods(&mut self) {
    self.pods = None;
  }

  pub fn set_resource(&mut self, resource: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ResourceMetricSource) {
    self.resource = Some(resource);
  }

  pub fn with_resource(mut self, resource: ::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ResourceMetricSource) -> IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
    self.resource = Some(resource);
    self
  }

  pub fn resource(&self) -> Option<&::models::IoK8sKubernetesPkgApisAutoscalingV2alpha1ResourceMetricSource> {
    self.resource.as_ref()
  }

  pub fn reset_resource(&mut self) {
    self.resource = None;
  }

  pub fn set__type(&mut self, _type: String) {
    self._type = _type;
  }

  pub fn with__type(mut self, _type: String) -> IoK8sKubernetesPkgApisAutoscalingV2alpha1MetricSpec {
    self._type = _type;
    self
  }

  pub fn _type(&self) -> &String {
    &self._type
  }


}



