/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
  #[serde(rename = "port")]
  port: Option<String>,
  /// Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.
  #[serde(rename = "protocol")]
  protocol: Option<String>
}

impl IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
  pub fn new() -> IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
    IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
      port: None,
      protocol: None
    }
  }

  pub fn set_port(&mut self, port: String) {
    self.port = Some(port);
  }

  pub fn with_port(mut self, port: String) -> IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
    self.port = Some(port);
    self
  }

  pub fn port(&self) -> Option<&String> {
    self.port.as_ref()
  }

  pub fn reset_port(&mut self) {
    self.port = None;
  }

  pub fn set_protocol(&mut self, protocol: String) {
    self.protocol = Some(protocol);
  }

  pub fn with_protocol(mut self, protocol: String) -> IoK8sKubernetesPkgApisExtensionsV1beta1NetworkPolicyPort {
    self.protocol = Some(protocol);
    self
  }

  pub fn protocol(&self) -> Option<&String> {
    self.protocol.as_ref()
  }

  pub fn reset_protocol(&mut self) {
    self.protocol = None;
  }

}



