/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sKubernetesPkgApiV1DaemonEndpoint : DaemonEndpoint contains information about a single Daemon endpoint.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApiV1DaemonEndpoint {
  /// Port number of the given endpoint.
  #[serde(rename = "Port")]
  port: i32
}

impl IoK8sKubernetesPkgApiV1DaemonEndpoint {
  /// DaemonEndpoint contains information about a single Daemon endpoint.
  pub fn new(port: i32) -> IoK8sKubernetesPkgApiV1DaemonEndpoint {
    IoK8sKubernetesPkgApiV1DaemonEndpoint {
      port: port
    }
  }

  pub fn set_port(&mut self, port: i32) {
    self.port = port;
  }

  pub fn with_port(mut self, port: i32) -> IoK8sKubernetesPkgApiV1DaemonEndpoint {
    self.port = port;
    self
  }

  pub fn port(&self) -> &i32 {
    &self.port
  }


}



