/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApimachineryPkgUtilIntstrIntOrString {
}

impl IoK8sApimachineryPkgUtilIntstrIntOrString {
  pub fn new() -> IoK8sApimachineryPkgUtilIntstrIntOrString {
    IoK8sApimachineryPkgUtilIntstrIntOrString {
    }
  }

}



