/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec : TokenReviewSpec is a description of the token authentication request.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec {
  /// Token is the opaque bearer token.
  #[serde(rename = "token")]
  token: Option<String>
}

impl IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec {
  /// TokenReviewSpec is a description of the token authentication request.
  pub fn new() -> IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec {
    IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec {
      token: None
    }
  }

  pub fn set_token(&mut self, token: String) {
    self.token = Some(token);
  }

  pub fn with_token(mut self, token: String) -> IoK8sKubernetesPkgApisAuthenticationV1TokenReviewSpec {
    self.token = Some(token);
    self
  }

  pub fn token(&self) -> Option<&String> {
    self.token.as_ref()
  }

  pub fn reset_token(&mut self) {
    self.token = None;
  }

}



