/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1ClientIpConfig : ClientIPConfig represents the configurations of Client IP based session affinity.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1ClientIpConfig {
  /// timeoutSeconds specifies the seconds of ClientIP type session sticky time. The value must be >0 && <=86400(for 1 day) if ServiceAffinity == \"ClientIP\". Default value is 10800(for 3 hours).
  #[serde(rename = "timeoutSeconds")]
  timeout_seconds: Option<i32>
}

impl V1ClientIpConfig {
  /// ClientIPConfig represents the configurations of Client IP based session affinity.
  pub fn new() -> V1ClientIpConfig {
    V1ClientIpConfig {
      timeout_seconds: None
    }
  }

  pub fn set_timeout_seconds(&mut self, timeout_seconds: i32) {
    self.timeout_seconds = Some(timeout_seconds);
  }

  pub fn with_timeout_seconds(mut self, timeout_seconds: i32) -> V1ClientIpConfig {
    self.timeout_seconds = Some(timeout_seconds);
    self
  }

  pub fn timeout_seconds(&self) -> Option<&i32> {
    self.timeout_seconds.as_ref()
  }

  pub fn reset_timeout_seconds(&mut self) {
    self.timeout_seconds = None;
  }

}



