/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1NodeSelectorTerm : A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1NodeSelectorTerm {
  /// A list of node selector requirements by node's labels.
  #[serde(rename = "matchExpressions")]
  match_expressions: Option<Vec<::models::V1NodeSelectorRequirement>>,
  /// A list of node selector requirements by node's fields.
  #[serde(rename = "matchFields")]
  match_fields: Option<Vec<::models::V1NodeSelectorRequirement>>
}

impl V1NodeSelectorTerm {
  /// A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
  pub fn new() -> V1NodeSelectorTerm {
    V1NodeSelectorTerm {
      match_expressions: None,
      match_fields: None
    }
  }

  pub fn set_match_expressions(&mut self, match_expressions: Vec<::models::V1NodeSelectorRequirement>) {
    self.match_expressions = Some(match_expressions);
  }

  pub fn with_match_expressions(mut self, match_expressions: Vec<::models::V1NodeSelectorRequirement>) -> V1NodeSelectorTerm {
    self.match_expressions = Some(match_expressions);
    self
  }

  pub fn match_expressions(&self) -> Option<&Vec<::models::V1NodeSelectorRequirement>> {
    self.match_expressions.as_ref()
  }

  pub fn reset_match_expressions(&mut self) {
    self.match_expressions = None;
  }

  pub fn set_match_fields(&mut self, match_fields: Vec<::models::V1NodeSelectorRequirement>) {
    self.match_fields = Some(match_fields);
  }

  pub fn with_match_fields(mut self, match_fields: Vec<::models::V1NodeSelectorRequirement>) -> V1NodeSelectorTerm {
    self.match_fields = Some(match_fields);
    self
  }

  pub fn match_fields(&self) -> Option<&Vec<::models::V1NodeSelectorRequirement>> {
    self.match_fields.as_ref()
  }

  pub fn reset_match_fields(&mut self) {
    self.match_fields = None;
  }

}



