/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1NetworkPolicyPeer : NetworkPolicyPeer describes a peer to allow traffic from. Only certain combinations of fields are allowed

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1NetworkPolicyPeer {
  /// IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be.
  #[serde(rename = "ipBlock")]
  ip_block: Option<::models::V1IpBlock>,
  /// Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.  If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
  #[serde(rename = "namespaceSelector")]
  namespace_selector: Option<::models::V1LabelSelector>,
  /// This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.  If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
  #[serde(rename = "podSelector")]
  pod_selector: Option<::models::V1LabelSelector>
}

impl V1NetworkPolicyPeer {
  /// NetworkPolicyPeer describes a peer to allow traffic from. Only certain combinations of fields are allowed
  pub fn new() -> V1NetworkPolicyPeer {
    V1NetworkPolicyPeer {
      ip_block: None,
      namespace_selector: None,
      pod_selector: None
    }
  }

  pub fn set_ip_block(&mut self, ip_block: ::models::V1IpBlock) {
    self.ip_block = Some(ip_block);
  }

  pub fn with_ip_block(mut self, ip_block: ::models::V1IpBlock) -> V1NetworkPolicyPeer {
    self.ip_block = Some(ip_block);
    self
  }

  pub fn ip_block(&self) -> Option<&::models::V1IpBlock> {
    self.ip_block.as_ref()
  }

  pub fn reset_ip_block(&mut self) {
    self.ip_block = None;
  }

  pub fn set_namespace_selector(&mut self, namespace_selector: ::models::V1LabelSelector) {
    self.namespace_selector = Some(namespace_selector);
  }

  pub fn with_namespace_selector(mut self, namespace_selector: ::models::V1LabelSelector) -> V1NetworkPolicyPeer {
    self.namespace_selector = Some(namespace_selector);
    self
  }

  pub fn namespace_selector(&self) -> Option<&::models::V1LabelSelector> {
    self.namespace_selector.as_ref()
  }

  pub fn reset_namespace_selector(&mut self) {
    self.namespace_selector = None;
  }

  pub fn set_pod_selector(&mut self, pod_selector: ::models::V1LabelSelector) {
    self.pod_selector = Some(pod_selector);
  }

  pub fn with_pod_selector(mut self, pod_selector: ::models::V1LabelSelector) -> V1NetworkPolicyPeer {
    self.pod_selector = Some(pod_selector);
    self
  }

  pub fn pod_selector(&self) -> Option<&::models::V1LabelSelector> {
    self.pod_selector.as_ref()
  }

  pub fn reset_pod_selector(&mut self) {
    self.pod_selector = None;
  }

}



