/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1TopologySelectorTerm : A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1TopologySelectorTerm {
  /// A list of topology selector requirements by labels.
  #[serde(rename = "matchLabelExpressions")]
  match_label_expressions: Option<Vec<::models::V1TopologySelectorLabelRequirement>>
}

impl V1TopologySelectorTerm {
  /// A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.
  pub fn new() -> V1TopologySelectorTerm {
    V1TopologySelectorTerm {
      match_label_expressions: None
    }
  }

  pub fn set_match_label_expressions(&mut self, match_label_expressions: Vec<::models::V1TopologySelectorLabelRequirement>) {
    self.match_label_expressions = Some(match_label_expressions);
  }

  pub fn with_match_label_expressions(mut self, match_label_expressions: Vec<::models::V1TopologySelectorLabelRequirement>) -> V1TopologySelectorTerm {
    self.match_label_expressions = Some(match_label_expressions);
    self
  }

  pub fn match_label_expressions(&self) -> Option<&Vec<::models::V1TopologySelectorLabelRequirement>> {
    self.match_label_expressions.as_ref()
  }

  pub fn reset_match_label_expressions(&mut self) {
    self.match_label_expressions = None;
  }

}



