/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1TopologySelectorLabelRequirement : A topology selector requirement is a selector that matches given label. This is an alpha feature and may change in the future.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1TopologySelectorLabelRequirement {
  /// The label key that the selector applies to.
  #[serde(rename = "key")]
  key: String,
  /// An array of string values. One value must match the label to be selected. Each entry in ::serde_json::Values is ORed.
  #[serde(rename = "values")]
  values: Vec<String>
}

impl V1TopologySelectorLabelRequirement {
  /// A topology selector requirement is a selector that matches given label. This is an alpha feature and may change in the future.
  pub fn new(key: String, values: Vec<String>) -> V1TopologySelectorLabelRequirement {
    V1TopologySelectorLabelRequirement {
      key: key,
      values: values
    }
  }

  pub fn set_key(&mut self, key: String) {
    self.key = key;
  }

  pub fn with_key(mut self, key: String) -> V1TopologySelectorLabelRequirement {
    self.key = key;
    self
  }

  pub fn key(&self) -> &String {
    &self.key
  }


  pub fn set_values(&mut self, values: Vec<String>) {
    self.values = values;
  }

  pub fn with_values(mut self, values: Vec<String>) -> V1TopologySelectorLabelRequirement {
    self.values = values;
    self
  }

  pub fn values(&self) -> &Vec<String> {
    &self.values
  }


}



