/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1alpha1VolumeAttachmentSource : VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1alpha1VolumeAttachmentSource {
  /// Name of the persistent volume to attach.
  #[serde(rename = "persistentVolumeName")]
  persistent_volume_name: Option<String>
}

impl V1alpha1VolumeAttachmentSource {
  /// VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.
  pub fn new() -> V1alpha1VolumeAttachmentSource {
    V1alpha1VolumeAttachmentSource {
      persistent_volume_name: None
    }
  }

  pub fn set_persistent_volume_name(&mut self, persistent_volume_name: String) {
    self.persistent_volume_name = Some(persistent_volume_name);
  }

  pub fn with_persistent_volume_name(mut self, persistent_volume_name: String) -> V1alpha1VolumeAttachmentSource {
    self.persistent_volume_name = Some(persistent_volume_name);
    self
  }

  pub fn persistent_volume_name(&self) -> Option<&String> {
    self.persistent_volume_name.as_ref()
  }

  pub fn reset_persistent_volume_name(&mut self) {
    self.persistent_volume_name = None;
  }

}



