/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.17
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1beta1HttpIngressRuleValue : HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last '/' and before the first '?' or '#'.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1beta1HttpIngressRuleValue {
  /// A collection of paths that map requests to backends.
  #[serde(rename = "paths")]
  paths: Vec<::models::V1beta1HttpIngressPath>
}

impl V1beta1HttpIngressRuleValue {
  /// HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last '/' and before the first '?' or '#'.
  pub fn new(paths: Vec<::models::V1beta1HttpIngressPath>) -> V1beta1HttpIngressRuleValue {
    V1beta1HttpIngressRuleValue {
      paths: paths
    }
  }

  pub fn set_paths(&mut self, paths: Vec<::models::V1beta1HttpIngressPath>) {
    self.paths = paths;
  }

  pub fn with_paths(mut self, paths: Vec<::models::V1beta1HttpIngressPath>) -> V1beta1HttpIngressRuleValue {
    self.paths = paths;
    self
  }

  pub fn paths(&self) -> &Vec<::models::V1beta1HttpIngressPath> {
    &self.paths
  }


}



