/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ExtensionsV1beta1AllowedFlexVolume : AllowedFlexVolume represents a single Flexvolume that is allowed to be used. Deprecated: use AllowedFlexVolume from policy API Group instead.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ExtensionsV1beta1AllowedFlexVolume {
  /// driver is the name of the Flexvolume driver.
  #[serde(rename = "driver")]
  driver: String
}

impl ExtensionsV1beta1AllowedFlexVolume {
  /// AllowedFlexVolume represents a single Flexvolume that is allowed to be used. Deprecated: use AllowedFlexVolume from policy API Group instead.
  pub fn new(driver: String) -> ExtensionsV1beta1AllowedFlexVolume {
    ExtensionsV1beta1AllowedFlexVolume {
      driver: driver
    }
  }

  pub fn set_driver(&mut self, driver: String) {
    self.driver = driver;
  }

  pub fn with_driver(mut self, driver: String) -> ExtensionsV1beta1AllowedFlexVolume {
    self.driver = driver;
    self
  }

  pub fn driver(&self) -> &String {
    &self.driver
  }


}



