/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1alpha1AggregationRule : AggregationRule describes how to locate ClusterRoles to aggregate into the ClusterRole

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1alpha1AggregationRule {
  /// ClusterRoleSelectors holds a list of selectors which will be used to find ClusterRoles and create the rules. If any of the selectors match, then the ClusterRole's permissions will be added
  #[serde(rename = "clusterRoleSelectors")]
  cluster_role_selectors: Option<Vec<::models::V1LabelSelector>>
}

impl V1alpha1AggregationRule {
  /// AggregationRule describes how to locate ClusterRoles to aggregate into the ClusterRole
  pub fn new() -> V1alpha1AggregationRule {
    V1alpha1AggregationRule {
      cluster_role_selectors: None
    }
  }

  pub fn set_cluster_role_selectors(&mut self, cluster_role_selectors: Vec<::models::V1LabelSelector>) {
    self.cluster_role_selectors = Some(cluster_role_selectors);
  }

  pub fn with_cluster_role_selectors(mut self, cluster_role_selectors: Vec<::models::V1LabelSelector>) -> V1alpha1AggregationRule {
    self.cluster_role_selectors = Some(cluster_role_selectors);
    self
  }

  pub fn cluster_role_selectors(&self) -> Option<&Vec<::models::V1LabelSelector>> {
    self.cluster_role_selectors.as_ref()
  }

  pub fn reset_cluster_role_selectors(&mut self) {
    self.cluster_role_selectors = None;
  }

}



