/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1beta1ExternalDocumentation : ExternalDocumentation allows referencing an external resource for extended documentation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1beta1ExternalDocumentation {
  #[serde(rename = "description")]
  description: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl V1beta1ExternalDocumentation {
  /// ExternalDocumentation allows referencing an external resource for extended documentation.
  pub fn new() -> V1beta1ExternalDocumentation {
    V1beta1ExternalDocumentation {
      description: None,
      url: None
    }
  }

  pub fn set_description(&mut self, description: String) {
    self.description = Some(description);
  }

  pub fn with_description(mut self, description: String) -> V1beta1ExternalDocumentation {
    self.description = Some(description);
    self
  }

  pub fn description(&self) -> Option<&String> {
    self.description.as_ref()
  }

  pub fn reset_description(&mut self) {
    self.description = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> V1beta1ExternalDocumentation {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



