/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V2beta2ObjectMetricSource : ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V2beta2ObjectMetricSource {
  #[serde(rename = "describedObject")]
  described_object: ::models::V2beta2CrossVersionObjectReference,
  /// metric identifies the target metric by name and selector
  #[serde(rename = "metric")]
  metric: ::models::V2beta2MetricIdentifier,
  /// target specifies the target value for the given metric
  #[serde(rename = "target")]
  target: ::models::V2beta2MetricTarget
}

impl V2beta2ObjectMetricSource {
  /// ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
  pub fn new(described_object: ::models::V2beta2CrossVersionObjectReference, metric: ::models::V2beta2MetricIdentifier, target: ::models::V2beta2MetricTarget) -> V2beta2ObjectMetricSource {
    V2beta2ObjectMetricSource {
      described_object: described_object,
      metric: metric,
      target: target
    }
  }

  pub fn set_described_object(&mut self, described_object: ::models::V2beta2CrossVersionObjectReference) {
    self.described_object = described_object;
  }

  pub fn with_described_object(mut self, described_object: ::models::V2beta2CrossVersionObjectReference) -> V2beta2ObjectMetricSource {
    self.described_object = described_object;
    self
  }

  pub fn described_object(&self) -> &::models::V2beta2CrossVersionObjectReference {
    &self.described_object
  }


  pub fn set_metric(&mut self, metric: ::models::V2beta2MetricIdentifier) {
    self.metric = metric;
  }

  pub fn with_metric(mut self, metric: ::models::V2beta2MetricIdentifier) -> V2beta2ObjectMetricSource {
    self.metric = metric;
    self
  }

  pub fn metric(&self) -> &::models::V2beta2MetricIdentifier {
    &self.metric
  }


  pub fn set_target(&mut self, target: ::models::V2beta2MetricTarget) {
    self.target = target;
  }

  pub fn with_target(mut self, target: ::models::V2beta2MetricTarget) -> V2beta2ObjectMetricSource {
    self.target = target;
    self
  }

  pub fn target(&self) -> &::models::V2beta2MetricTarget {
    &self.target
  }


}



