/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.12.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V2beta2PodsMetricStatus : PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V2beta2PodsMetricStatus {
  /// current contains the current value for the given metric
  #[serde(rename = "current")]
  current: ::models::V2beta2MetricValueStatus,
  /// metric identifies the target metric by name and selector
  #[serde(rename = "metric")]
  metric: ::models::V2beta2MetricIdentifier
}

impl V2beta2PodsMetricStatus {
  /// PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
  pub fn new(current: ::models::V2beta2MetricValueStatus, metric: ::models::V2beta2MetricIdentifier) -> V2beta2PodsMetricStatus {
    V2beta2PodsMetricStatus {
      current: current,
      metric: metric
    }
  }

  pub fn set_current(&mut self, current: ::models::V2beta2MetricValueStatus) {
    self.current = current;
  }

  pub fn with_current(mut self, current: ::models::V2beta2MetricValueStatus) -> V2beta2PodsMetricStatus {
    self.current = current;
    self
  }

  pub fn current(&self) -> &::models::V2beta2MetricValueStatus {
    &self.current
  }


  pub fn set_metric(&mut self, metric: ::models::V2beta2MetricIdentifier) {
    self.metric = metric;
  }

  pub fn with_metric(mut self, metric: ::models::V2beta2MetricIdentifier) -> V2beta2PodsMetricStatus {
    self.metric = metric;
    self
  }

  pub fn metric(&self) -> &::models::V2beta2MetricIdentifier {
    &self.metric
  }


}



