[package]
name = "kubernetes"
version = "0.1.0"
description = "Kubernetes rust client"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/ynqa/kubernetes-rust"
readme = "README.md"
keywords = ["kubernetes"]
categories = ["web-programming::http-client"]

[dependencies]
base64 = "0.9.3"
dirs = "1.0.4"
failure = "0.1.2"
reqwest = "0.9.2"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_yaml = "0.8.5"
openssl = "0.10.12"

[dev-dependencies]
tempfile = "3.0.4"
categories =["web-programming::http-client"]

[lib]
name = "kubernetes"
path = "src/lib.rs"

[dependencies.kubernetes]
version = "1.0.0-snapshot"
path = "kubernetes"
