[package]
name = "kubernetes-rust"
version = "0.1.0"
description = "Kubernetes rust client"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/ynqa/kubernetes-rust"
readme = "README.md"
keywords = ["kubernetes"]
categories =["web-programming::http-client"]

[lib]
name = "kubernetes_rust"
path = "src/lib.rs"

[dependencies.kubernetes]
path = "kubernetes"
