/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct AuthorizationV1beta1ApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> AuthorizationV1beta1ApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> AuthorizationV1beta1ApiClient<C> {
        AuthorizationV1beta1ApiClient {
            configuration: configuration,
        }
    }
}

pub trait AuthorizationV1beta1Api {
    fn create_authorization_v1beta1_namespaced_local_subject_access_review(&self, namespace: &str, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_local_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1LocalSubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1LocalSubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn create_authorization_v1beta1_self_subject_access_review(&self, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_self_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SelfSubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SelfSubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn create_authorization_v1beta1_subject_access_review(&self, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn get_authorization_v1beta1_api_resources(&self, ) -> Box<Future<Item = ::models::IoK8sApimachineryPkgApisMetaV1ApiResourceList, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>AuthorizationV1beta1Api for AuthorizationV1beta1ApiClient<C> {
    fn create_authorization_v1beta1_namespaced_local_subject_access_review(&self, namespace: &str, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_local_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1LocalSubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1LocalSubjectAccessReview, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/namespaces/{namespace}/localsubjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .with_query_param("pretty".to_string(), pretty.to_string())
            .with_path_param("namespace".to_string(), namespace.to_string())
            .with_body_param(io_k8s_kubernetes_pkg_apis_authorization_v1beta1_local_subject_access_review)
            .execute(self.configuration.borrow())
    }

    fn create_authorization_v1beta1_self_subject_access_review(&self, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_self_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SelfSubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SelfSubjectAccessReview, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/selfsubjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .with_query_param("pretty".to_string(), pretty.to_string())
            .with_body_param(io_k8s_kubernetes_pkg_apis_authorization_v1beta1_self_subject_access_review)
            .execute(self.configuration.borrow())
    }

    fn create_authorization_v1beta1_subject_access_review(&self, io_k8s_kubernetes_pkg_apis_authorization_v1beta1_subject_access_review: ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SubjectAccessReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthorizationV1beta1SubjectAccessReview, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/subjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .with_query_param("pretty".to_string(), pretty.to_string())
            .with_body_param(io_k8s_kubernetes_pkg_apis_authorization_v1beta1_subject_access_review)
            .execute(self.configuration.borrow())
    }

    fn get_authorization_v1beta1_api_resources(&self, ) -> Box<Future<Item = ::models::IoK8sApimachineryPkgApisMetaV1ApiResourceList, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/apis/authorization.k8s.io/v1beta1/".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .execute(self.configuration.borrow())
    }

}
