/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct AuthenticationV1ApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> AuthenticationV1ApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> AuthenticationV1ApiClient<C> {
        AuthenticationV1ApiClient {
            configuration: configuration,
        }
    }
}

pub trait AuthenticationV1Api {
    fn create_authentication_v1_token_review(&self, io_k8s_kubernetes_pkg_apis_authentication_v1_token_review: ::models::IoK8sKubernetesPkgApisAuthenticationV1TokenReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthenticationV1TokenReview, Error = Error<serde_json::Value>>>;
    fn get_authentication_v1_api_resources(&self, ) -> Box<Future<Item = ::models::IoK8sApimachineryPkgApisMetaV1ApiResourceList, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>AuthenticationV1Api for AuthenticationV1ApiClient<C> {
    fn create_authentication_v1_token_review(&self, io_k8s_kubernetes_pkg_apis_authentication_v1_token_review: ::models::IoK8sKubernetesPkgApisAuthenticationV1TokenReview, pretty: &str) -> Box<Future<Item = ::models::IoK8sKubernetesPkgApisAuthenticationV1TokenReview, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/apis/authentication.k8s.io/v1/tokenreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .with_query_param("pretty".to_string(), pretty.to_string())
            .with_body_param(io_k8s_kubernetes_pkg_apis_authentication_v1_token_review)
            .execute(self.configuration.borrow())
    }

    fn get_authentication_v1_api_resources(&self, ) -> Box<Future<Item = ::models::IoK8sApimachineryPkgApisMetaV1ApiResourceList, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/apis/authentication.k8s.io/v1/".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
            .execute(self.configuration.borrow())
    }

}
